import { StyleSheet } from 'react-native';
import { COLORS, BOX_SIZE } from './GestureHandlerExample.constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  content: {
    padding: 20,
    paddingBottom: 100,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.text,
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: COLORS.textMuted,
    textAlign: 'center',
    marginBottom: 30,
  },
  section: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 8,
  },
  sectionDescription: {
    fontSize: 13,
    color: COLORS.textMuted,
    marginBottom: 16,
    lineHeight: 20,
  },
  gestureArea: {
    height: 200,
    backgroundColor: COLORS.secondary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  draggableBox: {
    width: BOX_SIZE,
    height: BOX_SIZE,
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },
  boxText: {
    color: COLORS.text,
    fontWeight: '600',
    fontSize: 12,
  },
  zoomContainer: {
    width: '100%',
    height: 200,
    backgroundColor: COLORS.secondary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  zoomImage: {
    width: 150,
    height: 150,
    borderRadius: 12,
    backgroundColor: COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeContainer: {
    height: 150,
    justifyContent: 'center',
    alignItems: 'center',
  },
  swipeCard: {
    width: '90%',
    height: 120,
    backgroundColor: COLORS.primary,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  swipeCardText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: '600',
  },
  swipeHint: {
    color: COLORS.textMuted,
    fontSize: 12,
    marginTop: 8,
  },
  tapBox: {
    width: 150,
    height: 150,
    backgroundColor: COLORS.primary,
    borderRadius: 75,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tapCount: {
    color: COLORS.text,
    fontSize: 32,
    fontWeight: 'bold',
  },
  tapLabel: {
    color: COLORS.text,
    fontSize: 12,
    marginTop: 4,
  },
  explanationSection: {
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 20,
  },
  explanationTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.text,
    marginBottom: 12,
  },
  explanationText: {
    color: '#ccc',
    fontSize: 14,
    lineHeight: 22,
    marginBottom: 12,
  },
  bold: {
    fontWeight: 'bold',
    color: COLORS.text,
  },
  codeBlock: {
    backgroundColor: COLORS.secondary,
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  codeText: {
    color: COLORS.accent,
    fontSize: 12,
    fontFamily: 'monospace',
  },
  indicator: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 12,
    gap: 8,
  },
  indicatorDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: COLORS.textMuted,
  },
  indicatorDotActive: {
    backgroundColor: COLORS.accent,
  },
});